language: vim

before_script: |
  hg clone https://code.google.com/p/vim/
  cd vim
  # ./configure --with-features=huge --enable-rubyinterp --enable-pythoninterp
  ./configure --with-features=huge
  make
  sudo make install
  cd -

script: |
  make test
